# Generated by Django 5.1.6 on 2025-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(verbose_name='Масса'),
        ),
    ]
