# Generated by Django 5.1.6 on 2025-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_user_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_points_used',
            field=models.IntegerField(default=0),
        ),
    ]
